version: 0.1

phases:
  install:
     runtime-versions:
      java: 11
  pre_build:
    commands:
      - echo "Pre-building starting"
  build:
    commands:
      - echo "Starting building stage"
      - mvn clean package
  post_build:
    commands:
      - echo "Building complete"
  test: 
    commands:
      - echo "Starting testing stage"
      - mvn test 
artifacts:
  files:
    - target/cicd-example.jar
  discard-paths: yes
